### ISSUE TITLE
[Request] Set custom model name in modelOptions

### ISSUE THREAD

**Issue by FERNman** [hasezoey/typegoose#19] opened 2019-09-03 09:19 UTC
## Describe what you need | want

Currently, the class name is used as the model name in mongoose. In plain mongoose, there is the option to set a different model name.

This probably doesn't matter for most users, but I'm currently writing migrations for MongoDB where I have a few similar, but different versions of the same model. When using the same name for all of them, a lot of weird errors came up and it took me quite some time to figure out what the problem was.

## Do you have already an idea for the implementation?

Add an additional parameter to the `modelOptions` decorator, e.g. `modelName` and use it if it's present instead of the class name in `getModelForClass`.

**Comment by hasezoey** [comment] 2019-09-03 10:53
This is some duplicate of some issue, i will leave this open until found

**Comment by hasezoey** [comment] 2019-09-04 07:17
I think this issue can be left open, because it is the first one of this issue in this fork

additions:
<sub>thing that should be included / thought of</sub>
- https://github.com/szokodiakos/typegoose/pull/282 should probably be combined to
  - be either be used & appeneded to the name
  - or be an option for a custom or this above (AND make the above as automatic choice)

**Comment by hasezoey** [comment] 2019-09-04 08:46
Does [this](hasezoey.github.io/typegoose/guides/advanced/models-with-same-name/) solve the issue?

**Comment by hasezoey** [comment] 2019-09-05 12:50
closing because of:
https://hasezoey.github.io/typegoose/guides/advanced/models-with-same-name/

**Closed by hasezoey** 2019-09-05 12:50 UTC
Labels: enhancement
